# Generated by Django 2.1.dev20180114011155 on 2018-05-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180330_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='author',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
