# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='City Image'),
        ),
    ]
